### PR TITLE
fix: print regex error

### PR DESCRIPTION
**Pull request by MarcoIeni**
Before:
image

After:
image

### CODE REVIEW

**Comment by sassman** [comment]
nice, could you pls share the `username` that you have used to provoke this error? I'd like to reproduce it very identically.

**Comment by MarcoIeni** [comment]
yes, sure:

```toml
[placeholders.username]
type = "string"
prompt = "GitHub username (or organization)?"
regex = "/^[a-z\\d](?:[a-z\\d]|-(?=[a-z\\d])){0,38}$/i"
```

**Comment by MarcoIeni** [comment]
Probably I need to rename `placeholders.username` to `placeholders.gh-username`, because I see that `{{username}}` is now reserved :)

**Pull request merged**
