### PR TITLE
Add testcase for #201 (Test git history is removed)

### LINKED ISSUE #201: Test that git history is removed
cargo generate removes `.git` and then makes a blank one - this should be tested

### PR DESCRIPTION
**Pull request by taurr**
fixes #201

### CODE REVIEW

**Comment by taurr** [comment]
@sassman: Workflow in repo forks are broken - would be nice with a description of how to fix missing setup for the new SSH stuff, if checks must run successfully in order to contribute.

**Comment by sassman** [comment]
@taurr It's a feature apparently [read more](https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/)

I'm looking into it and try to find a solution

**Comment by sassman** [comment]
I created PR #382 to workaround this limitation for now, after merge you can rebase and then all the build checks should run as usual.

**Review by sassman — APPROVED** [review]

**Comment by sassman** [comment]
thanks @taurr and good to have you back!

**Pull request merged**
