### PR TITLE
Allow version requirement in `cargo-generate.toml`

### LINKED ISSUE #76: check template pkg metadata for cargo gen version, warn on mismatch
to help make it easier for us to proceed without breaking things, i'd like to propose that template authors be required to include a cargo-generate version in their cargo toml, e.g.

```
[package]
name = "{{project-name}}"
version = "0.1.0"
cargo-generate = "0.1.0"
```

if the version doesn't exist in the cargo toml, we should WARN
if the version of cargo-generate on disk is different than the listed version, we should WARN

this should be fully semver feature full, so folks should be able to write something like:
`cargo-generate = "~0.2.0"`

### PR DESCRIPTION
**Pull request by taurr**
closes #76

### CODE REVIEW

**Review by sassman — APPROVED** [review]
nice work

**Comment by sassman** [comment]
could you please rebase the branch?

**Review by sassman — APPROVED** [review]

**Comment by sassman** [comment]
needs again rebase, sorry for the overhead

**Comment by taurr** [comment]
I could just **not** make a lot of PR's for you... then I wouldn't have to rebase so often 🤣

**Review by sassman — APPROVED** [review]

**Pull request merged**
