### PR TITLE
Feat/327 proxy vars

### LINKED ISSUE #327: Got `SSL error` if using behind a proxy
### The Bug
I'm getting this error while trying to use `cargo generate` behind a proxy server:
```
Error:  Git Error: SSL error: syscall failure: Connection reset by peer; class=Os (2)
```
The cause seems to be related to the proxy settings on my machine, but since I have already set `HTTP_PROXY` and `HTTPS_PROXY` and the `git clone` command didn't give any error so I think this bug may be not about `git` itself but `cargo-generate`.

### Assumption
I think this bug is caused by the fact that `git::create` does not make connection using the proxy options even if there are proxy environment variables in the `git` configuration.

### Proposal
Force the `create` method in [`git.rs`](https://github.com/cargo-generate/cargo-generate/blob/master/src/git.rs) to use the proxy settings by default.
Change this:
```rust
pub(crate) fn create(project_dir: &Path, args: GitConfig) -> Result<String> {
    //
            git_remote.connect(git2::Direction::Fetch)?;
    //
}
```
To this:
```rust
pub(crate) fn create(project_dir: &Path, args: GitConfig) -> Result<String> {
    //
            let mut proxy = ProxyOptions::new();
            proxy.auto();
            git_remote.connect_auth(git2::Direction::Fetch, None, Some(proxy))?;
    //
}
```

### Environment information
- `cargo --version`:
```
cargo 1.51.0 (43b129a20 2021-03-16)
```
- `rustc --version`:
```
rustc 1.51.0 (2fd73fabe 2021-03-23)
```

### PR DESCRIPTION
**Pull request by sassman**
this PR should fix #327 

needs some verification.

/cc @joshrotenberg @metalwhale
would you please be so kind and have a look at this branch, if it actually works in your situation?

I've tested it with a local squid (http) proxy, and it seemed to work.

### CODE REVIEW

**Comment by joshrotenberg** [comment]
> this PR should fix #327
> 
> needs some verification.
> 
> /cc @joshrotenberg @metalwhale
> would you please be so kind and have a look at this branch, if it actually works in your situation?

I'll try to give a run today and see. Thanks for doing this!

**Comment by metalwhale** [comment]
Sorry for the late reply.
I haven't had time to take a test yet but had a look at the code and it seems good to me.
Thank you so much for fixing this for us!

**Comment by sassman** [comment]
hey @metalwhale @joshrotenberg 

did you had a chance to check if the PR would fix your issue?

**Comment by metalwhale** [comment]
@sassman 
I have test the code of `feat/327-proxy-vars` as following and it seemed to work very fine.
### 1. Test with `cargo test`
- Clone [`cargo-generate`](https://github.com/cargo-generate/cargo-generate) repository
- Run `cargo test` and got this failure:
```
test favorites::favorites_default_to_git_if_not_defined ... FAILED
```
```
failures:

---- favorites::favorites_default_to_git_if_not_defined stdout ----
thread 'favorites::favorites_default_to_git_if_not_defined' panicked at 'Unexpected stderr, failed var.contains("status code: 404")
└── var as str: Error:  Git Error: SSL error: syscall failure: Connection reset by peer; class=Os (2)



command=`"/tmp/cargo-generate/target/debug/cargo-generate" "generate" "--config" "/tmp/.tmpS8Bor3/cargo-generate" "--name" "favorite-project" "dummy"`
code=1
stdout=```" Favorite dummy not found in config, using it as a git repo url\n Creating project called `favorite-project`...\n"```
stderr=```"Error:  Git Error: SSL error: syscall failure: Connection reset by peer; class=Os (2)\n"```
', /home/node/.cargo/registry/src/github.com-1ecc6299db9ec823/assert_cmd-1.0.4/src/assert.rs:425:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    favorites::favorites_default_to_git_if_not_defined

test result: FAILED. 35 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.33s

error: test failed, to rerun pass '--test integration'
```
- Checkout to `feat/327-proxy-vars` branch
- Run `cargo test` again and confirmed it finished successfully!!

### 2. Test with subcommand
- Install the `generate` subcommand:
```
cargo install --git https://github.com/cargo-generate/cargo-generate --branch feat/327-proxy-vars
```
- Try to initialize some project using `cargo-generate`:
```
cargo generate --git https://github.com/rustwasm/wasm-pack-template
```
Got this error:
```
warning: spurious network error (2 tries remaining): SSL error: syscall failure: Connection reset by peer; class=Os (2)
warning: spurious network error (1 tries remaining): SSL error: syscall failure: Connection reset by peer; class=Os (2)
```
- Add these lines to `~/.cargo/config`:
```
[net]
git-fetch-with-cli = true
```
- Run `cargo generate` again and it worked like a charm!!

**Comment by sassman** [comment]
@metalwhale Thanks a lot for the very details and the testing.

I will try to investigate the errors you got there.
IMO it should eventually (ideally) work without the cargo config change. 

Let's see if that is possible or not.

**Comment by joshrotenberg** [comment]
Installing with the branch and then running works for me behind our proxy! 

I also happen to have net.git-fetch-with-cli = true because we use an internal crates registry. 

Incidentally, I also get the error @metalwhale gets when running cargo test.

**Pull request merged**
