### PR TITLE
release(0.9.0) version bump, readme, changelog

### PR DESCRIPTION
**Pull request by sassman**
probably the biggest release in my cargo-generate maintainer history, huge thanks to all you big efforts!

Without you this would never have been possible!!

@taurr @MarcoIeni @dave-tucker @orhun

### CODE REVIEW

**Comment by taurr** [comment]
If you like PR #431 you can get 1 important feature more into 0.9.0 😄

**Comment by sassman** [comment]
@taurr I think we are already pretty packed with features. I will test the upcoming one rather thoroughly and not jumping the gun now.

**Comment by MarcoIeni** [comment]
Thank you sassman for putting so much love in this awesome project :D

**Pull request merged**
